# 分类模型本地推理配置

data:
  labels:
    - "afternoon_peak"
    - "all_day_low"
    - "day_low_night_high"
    - "morning_peak"

model:
  num_boost_round: 2000

train:
  output_dir: "../models_agent/checkpoints/classification/xgboost"

predict:
  checkpoint_path: "../models_agent/checkpoints/classification/xgboost/best_model.json"
  batch_size: 128
